# TotemEffect by MinekCz 2.0.0
# Remove config after each update


# Join Totem with title
# You can use /jointotem

jointitle: "§a§lWelcome to"


joinsubtitle: "§l§aExample Server"

# -----------------------------


# Title with Totem 
# You can use /titletotem


totemtitle: "§a§lExample Title"


totemsubtitle: "§l§aExample SubTitle"

# ------------------------------


# Get Totem
# You can use /gettotem


# Custom totem name
totem_name: "§6§lExampleName"

# Don't change this unless you know what you're doing
totem_tag: "totem"


